name: hayyu_boki_project
description: "Hayyu Boki"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  package_info_plus: ^8.1.2
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  flutter_svg: ^2.0.5
  hugeicons: ^1.1.0
  fluttertoast: ^9.0.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^12.0.1
  flutter_icon_snackbar: ^1.2.1
  flutter_cache_manager: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/