name: hayyu_boki_project
description: "Hayyu Boki"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 #android ios linux macos web windows
  get: ^4.6.6 #android ios linux macos web windows
  package_info_plus: ^8.1.2 #android ios linux macos web windows
  flutter_gen_runner: ^5.8.0 #android ios linux macos windows
  build_runner: ^2.4.13 #linux macos windows
  flutter_svg: ^2.0.5 #android ios linux macos web windows
  hugeicons: ^1.1.0 #android ios linux macos web windows
  fluttertoast: ^9.0.0 #android ios web
  cached_network_image: ^3.4.1 #android ios linux macos web windows
  flutter_staggered_grid_view: ^0.7.0 #android ios linux macos web windows
  permission_handler: ^12.0.1 #android ios web windows
  flutter_icon_snackbar: ^1.2.1 #android ios linux macos web windows
  flutter_cache_manager: any #android ios linux macos web windows
  rename_app: ^1.6.5 #android ios linux macos windows
  change_app_package_name: ^1.5.0 #android ios linux macos windows
  flutter_launcher_icons: ^0.14.4 #android ios linux macos windows

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/